import mongoose, { Schema } from 'mongoose';

/**
 * Alert Model
 * 
 * Purpose: Store exception alerts for Contracts Managers
 * Used in CM-03 (Exception Alert Review)
 * 
 * Business Rules:
 * - Alerts are auto-generated by alert engine
 * - Alerts can be acknowledged or resolved
 * - Critical alerts require immediate attention
 * - Alerts are linked to sites and related entities
 */
const AlertSchema = new Schema(
  {
    // Alert type
    type: {
      type: String,
      enum: [
        'cost_variance',
        'missed_daily_log',
        'high_incident_rate',
        'low_attendance',
        'missing_timesheet',
        'budget_exceeded',
        'delayed_delivery',
        'safety_concern',
        'pending_variations',
        'high_cost_variation',
        'critical_incident',
        'overdue_training',
        'inspection_issue',
        'other',
      ],
      required: true,
      index: true,
    },

    // Alert severity
    severity: {
      type: String,
      enum: ['critical', 'warning', 'info'],
      required: true,
      default: 'warning',
      index: true,
    },

    // Site this alert is for
    siteId: {
      type: Schema.Types.ObjectId,
      ref: 'Site',
      required: true,
      index: true,
    },

    // Alert title
    title: {
      type: String,
      required: true,
      maxlength: 200,
      trim: true,
    },

    // Alert description/details
    description: {
      type: String,
      required: true,
      maxlength: 1000,
      trim: true,
    },

    // Alert status
    status: {
      type: String,
      enum: ['active', 'acknowledged', 'resolved'],
      default: 'active',
      required: true,
      index: true,
    },

    // Who acknowledged this alert
    acknowledgedBy: {
      type: Schema.Types.ObjectId,
      ref: 'Employee',
    },
    acknowledgedAt: {
      type: Date,
    },
    acknowledgmentNotes: {
      type: String,
      maxlength: 500,
      trim: true,
    },

    // Who resolved this alert
    resolvedBy: {
      type: Schema.Types.ObjectId,
      ref: 'Employee',
    },
    resolvedAt: {
      type: Date,
    },
    resolutionNotes: {
      type: String,
      maxlength: 500,
      trim: true,
    },

    // Flexible metadata for different alert types
    metadata: {
      type: Schema.Types.Mixed,
      default: {},
    },

    // Related entity (e.g., daily log, payroll run, attendance)
    relatedEntityType: {
      type: String,
      enum: ['daily_log', 'payroll_run', 'attendance', 'timesheet', 'incident', 'variation', 'other'],
    },
    relatedEntityId: {
      type: Schema.Types.ObjectId,
    },

    // Alert generation date
    generatedAt: {
      type: Date,
      default: Date.now,
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes for performance
AlertSchema.index({ siteId: 1, status: 1, severity: 1 });
AlertSchema.index({ type: 1, status: 1 });
AlertSchema.index({ status: 1, severity: 1, generatedAt: -1 });
AlertSchema.index({ siteId: 1, type: 1, status: 1 });

/**
 * Instance method: Acknowledge alert
 */
AlertSchema.methods.acknowledge = function (acknowledgedBy, notes) {
  if (this.status !== 'active') {
    throw new Error('Can only acknowledge active alerts');
  }

  this.status = 'acknowledged';
  this.acknowledgedBy = acknowledgedBy;
  this.acknowledgedAt = new Date();
  if (notes) {
    this.acknowledgmentNotes = notes;
  }

  return this.save();
};

/**
 * Instance method: Resolve alert
 */
AlertSchema.methods.resolve = function (resolvedBy, notes) {
  if (this.status === 'resolved') {
    throw new Error('Alert is already resolved');
  }

  this.status = 'resolved';
  this.resolvedBy = resolvedBy;
  this.resolvedAt = new Date();
  if (notes) {
    this.resolutionNotes = notes;
  }

  return this.save();
};

/**
 * Static method: Get active alerts count for a site
 */
AlertSchema.statics.getActiveCount = async function (siteId) {
  return this.countDocuments({
    siteId,
    status: 'active',
  });
};

/**
 * Static method: Get critical alerts count
 */
AlertSchema.statics.getCriticalCount = async function (siteId = null) {
  const query = {
    severity: 'critical',
    status: 'active',
  };
  if (siteId) {
    query.siteId = siteId;
  }
  return this.countDocuments(query);
};

export const Alert =
  mongoose.models.Alert || mongoose.model('Alert', AlertSchema);

