import mongoose, { Schema } from 'mongoose';
import crypto from 'crypto';

/**
 * SiteQRToken Model
 * 
 * Purpose: Store unique QR tokens for each site
 * Used for site-specific QR code generation and validation
 * 
 * Business Rules:
 * - Each site has one active QR token
 * - Tokens can be regenerated (invalidates old token)
 * - Token format: site_id + random token
 */
const SiteQRTokenSchema = new Schema(
  {
    // Site reference
    siteId: {
      type: Schema.Types.ObjectId,
      ref: 'Site',
      required: true,
      unique: true,
      index: true,
    },
    
    // Unique token (site_id + random string)
    token: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    
    // QR code data (JSON string to encode in QR)
    qrData: {
      type: String,
      required: true,
    },
    
    // QR code image (base64 data URL)
    qrImage: {
      type: String,
    },
    
    // Whether this token is active
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },
    
    // Generated at timestamp
    generatedAt: {
      type: Date,
      default: Date.now,
    },
    
    // Generated by (HR/Admin)
    generatedBy: {
      type: Schema.Types.ObjectId,
      ref: 'Employee',
    },
  },
  {
    timestamps: true,
  }
);

// Index for finding active tokens
SiteQRTokenSchema.index({ siteId: 1, isActive: 1 });

/**
 * Static method: Generate new token for a site
 */
SiteQRTokenSchema.statics.generateToken = async function(siteId, generatedBy = null) {
  // Generate random token
  const randomToken = crypto.randomBytes(16).toString('hex');
  const token = `${siteId}_${randomToken}`;
  
  // QR data to encode
  const qrData = JSON.stringify({
    type: 'site_attendance',
    siteId: siteId.toString(),
    token: randomToken,
    version: '1.0',
  });
  
  return {
    token,
    qrData,
  };
};

/**
 * Static method: Get or create token for a site
 */
SiteQRTokenSchema.statics.getOrCreateToken = async function(siteId, generatedBy = null) {
  let tokenDoc = await this.findOne({
    siteId,
    isActive: true,
  });
  
  if (!tokenDoc) {
    // Generate new token
    const { token, qrData } = await this.generateToken(siteId, generatedBy);
    
    tokenDoc = await this.create({
      siteId,
      token,
      qrData,
      generatedBy,
    });
  }
  
  return tokenDoc;
};

/**
 * Static method: Regenerate token for a site (invalidates old)
 */
SiteQRTokenSchema.statics.regenerateToken = async function(siteId, generatedBy = null) {
  // Deactivate old token
  await this.updateMany(
    { siteId, isActive: true },
    { isActive: false }
  );
  
  // Generate new token
  const { token, qrData } = await this.generateToken(siteId, generatedBy);
  
  const newToken = await this.create({
    siteId,
    token,
    qrData,
    generatedBy,
    generatedAt: new Date(),
  });
  
  return newToken;
};

/**
 * Static method: Resolve site from token
 */
SiteQRTokenSchema.statics.resolveSiteFromToken = async function(token) {
  const tokenDoc = await this.findOne({
    token,
    isActive: true,
  }).populate('siteId');
  
  if (!tokenDoc || !tokenDoc.siteId) {
    return null;
  }
  
  return tokenDoc.siteId;
};

export const SiteQRToken =
  mongoose.models.SiteQRToken || mongoose.model('SiteQRToken', SiteQRTokenSchema);



